version: '3.8'

services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=productos'
      - 'MYSQL_ROOT_PASSWORD=123456'
      - 'MYSQL_USER=irvin'
      - 'MYSQL_PASSWORD=123456'
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - mysql
    environment:
      - NODE_ENV=production

volumes:
  mysql_data:
